name: libusb_android_helper
description: "A helper plugin for libusb_android to request USB permission and device handle."
version: 1.0.1
repository: https://github.com/Scavanger/libusb_android_helper

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scavanger.libusb_android_helper
        pluginClass: LibusbAndroidHelperPlugin

