name: Publish to pub.dev

on:
  push:
    tags: 
    - 'v[0-9]+.[0-9]+.[0-9]+*' # tag pattern on pub.dev: 'v{{version}'
  workflow_dispatch:

jobs:
  publish:
    environment: 'pub.dev'
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
    - name: 📚 Git Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: ./.github/actions/publish_flutter_package
